name: githubactions_new
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello fan team"
      - name: print hi
        run: echo "hi team new"
